### ISSUE TITLE
Release of training code

### ISSUE THREAD

**Issue by skrya** [GaussianCube/GaussianCube#1]
Dear Authors, 

Thanks for the excellent work!!

Could you please inform us about your planned timeline for releasing the data fitting and training code?

Best

**Comment by GaussianCube** [comment]
Thank you for your interests in our work. We are currently in the final stages of testing and optimization to ensure the highest quality and performance. We plan to release the code in early May. We appreciate your patience and are excited to share our work with you soon.

**Comment by Friedrich-M** [comment]
Thank you for your excellent work! I would like to keep track of the training code release process. I hope we can contribute further based on this.

**Comment by GaussianCube** [comment]
Sorry for late reply. We will release the training code in the following weeks, please stay tuned. Thanks!

**Comment by GaussianCube** [comment]
We have released the GaussianCube construction and diffusion training code, feel free to try it!
