### ISSUE TITLE
objaverse object list for training

### ISSUE THREAD

**Issue by jwubz123** [GaussianCube/GaussianCube#4]
Dear Authors,

Thanks for the excellent work!! Is it possible to release the objaverse object list for training?

Best

**Comment by GaussianCube** [comment]
Hi, you can find our training list here: [objaverse_train.txt](https://github.com/user-attachments/files/15722446/objaverse_train.txt).

**Comment by jwubz123** [comment]
Thanks a lot for your gracious response.!!!
