### ISSUE TITLE
Obtaining mesh file from the generated output

### ISSUE THREAD

**Issue by hangzhou188** [GaussianCube/GaussianCube#7]
Hi, I test your pre-trained model on ShapeNet-car and the rendered video is quite impressive. I wonder if there is a way to export a mesh file in the format of .obj or .ply of the object? Thanks a lot!

**Comment by GaussianCube** [comment]
Hi, we have updated a script to convert the gaussians to mesh following (LGM)[https://github.com/3DTopia/LGM/blob/main/convert.py], which first fits a NeRF on Gaussian's renderings and then convert the fitted NeRF to mesh.
Please check https://github.com/GaussianCube/GaussianCube?tab=readme-ov-file#mesh-conversion for more details.

**Comment by hangzhou188** [comment]
Thank you, I will try it out!
