### ISSUE TITLE
Release  of fitted Gaussians on ShapeNet

### ISSUE THREAD

**Issue by wangwhTj** [GaussianCube/GaussianCube#8]
Thanks for this outstanding work! Are the fitted Gaussians on ShapeNet Chair available?

**Comment by GaussianCube** [comment]
Hi,

Thank you for reaching out and for your interest in our work with the ShapeNet dataset. 

In accordance with the ShapeNet Terms of Use, we recommend that you directly obtain the ShapeNet data by registering for an account and agreeing to the licensing conditions set forth by Princeton University and Stanford University. The dataset is intended for non-commercial research and educational purposes, and it is important to adhere to these terms when utilizing ShapeNet resources.

Once you have obtained the ShapeNet data under the appropriate license, you can use our GaussianCube fitting code on our [GitHub repository](https://github.com/GaussianCube/GaussianCube_Construction). With this script, you will be able to render the 3D models and fit Gaussian representations to the data as required for your specific research needs.

By following this approach, you ensure compliance with the licensing agreement, and it also facilitates the sustainability of the ShapeNet community and the respect for the intellectual property rights of the contributors.

**Comment by wangwhTj** [comment]
Got it, thanks for your reply!
